/**
 * Onboarding Schemas Index
 *
 * 📍 src/features/onboarding/schemas/index.ts
 */

export {
  type AreaOfInterest,
  AreaOfInterestSchema,
  type AreasOfInterestResponse,
  AreasOfInterestResponseSchema,
  type Endgoal,
  EndgoalSchema,
  type Pathway,
  PathwaySchema,
  type SelectDomainsRequest,
  SelectDomainsRequestSchema,
  SelectDomainsResponseSchema,
  type SelectEndgoalsRequest,
  SelectEndgoalsRequestSchema,
  SelectEndgoalsResponseSchema,
} from "./interests.schema";
export {
  type College,
  CollegeSchema,
  type CollegesResponse,
  CollegesResponseSchema,
  type CompaniesResponse,
  CompaniesResponseSchema,
  type Company,
  CompanySchema,
  CountriesResponseSchema,
  type Country,
  CountrySchema,
  type CreateOrganizationRequest,
  CreateOrganizationRequestSchema,
  CreateOrganizationResponseSchema,
  type Department,
  DepartmentSchema,
  type DepartmentsResponse,
  DepartmentsResponseSchema,
  type District,
  DistrictSchema,
  DistrictsResponseSchema,
  type Role,
  RoleSchema,
  type RolesResponse,
  RolesResponseSchema,
  type SelectOrganizationRequest,
  SelectOrganizationRequestSchema,
  SelectOrganizationResponseSchema,
  type State,
  StateSchema,
  StatesResponseSchema,
} from "./organization.schema";
